"""Execute both pipeline versions AS A DATABRICKS JOB (serverless one-time run).

Ripple generates a self-contained Python script that embeds the base and head sources of
the entry file, reads the input snapshot for ``run_id`` from the Delta table
``workspace.ripple.raw_transactions``, executes both versions inside the job, and writes
both outputs to ``clean_transactions`` / ``daily_revenue`` tagged ``version = base|head``.
Because the job reads and writes Delta tables through Spark, Unity Catalog records the
lineage ``raw_transactions -> clean_transactions / daily_revenue`` for the run.

Everything goes through the ``databricks`` CLI (profile from the CLI config; no secrets).
"""

from __future__ import annotations

import json
import re
import subprocess
import time
from pathlib import Path

from ripple.databricks_backend import SCHEMA, DatabricksError, _api

JOB_SCRIPT = '''# Generated by Ripple: executes BASE and HEAD of {entry_file}:{entry_symbol} over one snapshot.
import types

RUN_ID = {run_id!r}
SCHEMA = {schema!r}
ENTRY = {entry_symbol!r}
SOURCES = {{"base": {base_src!r}, "head": {head_src!r}}}
CLEAN = "run_id string, version string, txn_id string, txn_date string, customer_id string, kind string, amount double"
DAILY = "run_id string, version string, txn_date string, net_revenue double, txn_count int"

from pyspark.sql import SparkSession
from pyspark.sql.functions import col
spark = SparkSession.builder.getOrCreate()


def load(src, name):
    mod = types.ModuleType(name)
    exec(compile(src, f"<{{name}}>", "exec"), mod.__dict__)
    return mod


def q(v):
    return "'" + str(v).replace("'", "''") + "'"


rows = [r.asDict() for r in spark.sql(
    f"SELECT txn_id, CAST(txn_date AS STRING) AS txn_date, customer_id, kind, amount "
    f"FROM {{SCHEMA}}.raw_transactions WHERE run_id = {{q(RUN_ID)}} ORDER BY txn_id").collect()]
if not rows:
    raise SystemExit(f"no snapshot rows for run_id {{RUN_ID}}")

summary = {{}}
for version, src in SOURCES.items():
    out = getattr(load(src, f"ripple_{{version}}"), ENTRY)([dict(r) for r in rows])
    for table, schema in (("clean_transactions", CLEAN), ("daily_revenue", DAILY)):
        spark.sql(f"DELETE FROM {{SCHEMA}}.{{table}} WHERE run_id = {{q(RUN_ID)}} AND version = {{q(version)}}")
        data = [{{"run_id": RUN_ID, "version": version, **r}} for r in out[table]]
        df = spark.createDataFrame(data, schema=schema).withColumn("txn_date", col("txn_date").cast("date"))
        df.write.mode("append").saveAsTable(f"{{SCHEMA}}.{{table}}")
        summary[f"{{version}}.{{table}}"] = len(data)
import json
print("RIPPLE_SUMMARY " + json.dumps(summary))
'''


def render_job_script(run_id: str, entry_file: str, entry_symbol: str, base_src: str, head_src: str,
                      schema: str = SCHEMA) -> str:
    return JOB_SCRIPT.format(run_id=run_id, entry_file=entry_file, entry_symbol=entry_symbol,
                             base_src=base_src, head_src=head_src, schema=schema)


def submit_body(run_name: str, python_file: str, environment_key: str = "ripple_env",
                timeout_seconds: int = 900) -> dict:
    """One-time serverless run: a single spark_python_task on a workspace file."""
    return {
        "run_name": run_name,
        "tasks": [{
            "task_key": "ripple_execute",
            "spark_python_task": {"python_file": python_file, "source": "WORKSPACE"},
            "environment_key": environment_key,
            "timeout_seconds": timeout_seconds,
        }],
        "environments": [{"environment_key": environment_key, "spec": {"client": "4"}}],
    }


def _cli(*args: str, timeout: int = 120) -> str:
    try:
        proc = subprocess.run(["databricks", *args], capture_output=True, text=True, timeout=timeout)
    except FileNotFoundError as exc:
        raise DatabricksError("databricks CLI not found") from exc
    except subprocess.TimeoutExpired as exc:
        raise DatabricksError(f"databricks CLI timed out: {' '.join(args[:2])}") from exc
    if proc.returncode != 0:
        raise DatabricksError(proc.stderr.strip()[:500] or proc.stdout[:500])
    return proc.stdout


def current_user() -> str:
    return json.loads(_cli("current-user", "me", "--output", "json"))["userName"]


def upload_script(script: str, run_id: str, workdir: Path, user: str | None = None) -> str:
    """Write the script locally (evidence) and import it as a workspace file; returns the workspace path."""
    user = user or current_user()
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", run_id)
    local = workdir / f"ripple_exec_{safe}.py"
    local.parent.mkdir(parents=True, exist_ok=True)
    local.write_text(script)
    folder = f"/Workspace/Users/{user}/ripple"
    target = f"{folder}/ripple_exec_{safe}.py"
    _cli("workspace", "mkdirs", folder)
    _cli("workspace", "import", target, "--file", str(local), "--format", "AUTO", "--overwrite")
    return target


def run_job(python_file: str, run_name: str, poll_seconds: float = 5.0, max_wait: int = 900) -> dict:
    """Submit the one-time run and poll until it terminates. Raises DatabricksError on failure."""
    body = submit_body(run_name, python_file)
    resp = _api("post", "/api/2.2/jobs/runs/submit", body)
    run_id = resp.get("run_id")
    if run_id is None:
        raise DatabricksError(f"runs/submit returned no run_id: {json.dumps(resp)[:300]}")
    started = time.time()
    run: dict = {}
    while time.time() - started < max_wait:
        run = _api("get", f"/api/2.2/jobs/runs/get?run_id={run_id}")
        life = (run.get("state") or {}).get("life_cycle_state") or (run.get("status") or {}).get("state")
        if life in ("TERMINATED", "INTERNAL_ERROR", "SKIPPED"):
            break
        time.sleep(poll_seconds)
    state = run.get("state") or {}
    status = run.get("status") or {}
    result = state.get("result_state") or (status.get("termination_details") or {}).get("code")
    info = {
        "run_id": run_id,
        "run_name": run_name,
        "run_page_url": run.get("run_page_url"),
        "life_cycle_state": state.get("life_cycle_state") or status.get("state"),
        "result_state": result,
        "state_message": state.get("state_message") or (status.get("termination_details") or {}).get("message", ""),
        "duration_s": round(((run.get("end_time") or 0) - (run.get("start_time") or 0)) / 1000, 1) if run.get("end_time") else None,
        "python_file": python_file,
        "compute": "serverless",
    }
    if result != "SUCCESS":
        raise DatabricksError(f"job run {run_id} ended {info['life_cycle_state']}/{result}: {info['state_message'][:300]}")
    return info


def execute_on_databricks(run_id: str, entry_file: str, entry_symbol: str, base_src: str, head_src: str,
                          run_name: str, evidence_dir: Path) -> dict:
    """Generate, upload and run the job for ``run_id``. Snapshot must already be published."""
    script = render_job_script(run_id, entry_file, entry_symbol, base_src, head_src)
    python_file = upload_script(script, run_id, evidence_dir / "jobs")
    info = run_job(python_file, run_name)
    local = evidence_dir / "jobs" / Path(python_file).name
    try:
        info["script_local"] = str(local.relative_to(Path.cwd()))
    except ValueError:
        info["script_local"] = str(local)
    return info
